CREATE TABLE STUDENT1
(
STUDENTID INT(11) PRIMARY KEY,
STUDENTNAME VARCHAR(100),
MARKS INT(3)
);

CREATE TABLE COURSES1
(
COURSEID INT(11) PRIMARY KEY,
COURSENAME VARCHAR(100),
DURATION INT(2)
);

CREATE TABLE STUDENTS_COURSES
(
STUDENT_ID INT(11),
COURSE_ID INT(11)
);