CREATE TABLE PAYMENT (
   pid INT NOT NULL AUTO_INCREMENT,
   dcolumn VARCHAR(20) DEFAULT NULL,
   amt DOUBLE(7,2) DEFAULT NULL,
   cctype VARCHAR(10) DEFAULT NULL,
   cqtype VARCHAR(10) DEFAULT NULL,
   PRIMARY KEY(pid)
);